import mongoose, { Schema } from "mongoose";

const tripPlaceSchema = new Schema({
  trip: { type: Schema.Types.ObjectId, ref: "Trip", index: true },

  name: String,
  description: String,

  location: {
    lat: Number,
    lng: Number,
  },

  category: String, // temple, valley, market

  rating: Number,
  source: {
    type: String,
    enum: ["google", "opentripmap", "ai"],
  },

  photos: [String],

  autoGenerated: { type: Boolean, default: true },
});

export const TripPlace = mongoose.model("TripPlace", tripPlaceSchema);
